### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by TalEdd** [j-tai/TieFix#1]
[crash-2021-12-08_15.02.07-client.txt](https://github.com/j-tai/TieFix/files/7673982/crash-2021-12-08_15.02.07-client.txt)
Crashes instantly on launch with a bunch of mods enabled. Not sure incompatibility with what.

**Comment by j-tai** [comment]
Looks like this is an incompatibility with Bedrockify, as [they redirect](https://github.com/juancarloscp52/BedrockIfy/blob/56e567f8e10d85981b62a52d925d706f9c778b2f/src/main/java/me/juancarloscp52/bedrockify/mixin/client/features/screenSafeArea/InGameHudMixin.java#L192) the same call that [we redirect](https://github.com/j-tai/TieFix/blob/ba280d9b83167de9a0d25c080856cc16e8f62d4b/src/main/java/ca/jtai/tiefix/mixin/mc145929/InGameHudMixin.java#L14).

Could you try using this build? [TieFix-dev.zip](https://github.com/j-tai/TieFix/files/7677899/TieFix-dev.zip) Unzip this and install the jar inside.
Please let me know if it still crashes.

**Comment by TalEdd** [comment]
Seems to be working. Thank you!

**Comment by j-tai** [comment]
Thanks! The next release will contain the fix. You can keep using that build in the meantime.
