### ISSUE TITLE
Backport for 1.18?

### ISSUE THREAD

**Issue by akiyuee** [j-tai/TieFix#12]
Like a lot of ppl still sticks to 1.18, including me.

**Comment by j-tai** [comment]
I don't have plans to support multiple Minecraft versions at a time, unfortunately.

Here's a build of the mod just before it was updated to 1.19, which should contain the latest fixes: [TieFix-1.10.0-310a6fe.zip](https://github.com/j-tai/TieFix/files/8882869/TieFix-1.10.0-310a6fe.zip)
You can use this one with 1.18.2.

Next time a new Minecraft version is released, I'll make two releases of this mod: one for the previous MC version (which will be the last release for that version) and one for the new MC version, both containing the latest additions.
