### ISSUE TITLE
Maybe add some of the bugs from random patches?

### ISSUE THREAD

**Issue by lostopkk** [j-tai/TieFix#6]
Random patches is a mod that got stuck in 1.16.5, and it's a mod that helped me a lot through settings and bug fixes.  So I looked at that the project uses the MIT License (which would be a pretty permissive license on code change or portability), and I looked at tiefix and figured it was just a one-time improvement from random patches... so maybe if there's a possibility porting some bugs from random patches would be of great help to the folks at 1.18.1

The mod: https://github.com/TheRandomLabs/RandomPatches

**Comment by j-tai** [comment]
I can definitely add some. Just need to figure out how to give attribution.
