### ISSUE TITLE
List of client-side bugs.

### ISSUE THREAD

**Issue by Kichura** [j-tai/TieFix#8]
This is sorta my second attempt but a grabbed list of client-side bugs from debugify as that mod was kinda controversial due to it not having an anti-telemetry option + using checks for bug fixes which i was dissatisified about (mainly server verification context and update checker...?),

[List of bugs here;](https://pastebin.com/raw/kPhS3FN1) otherwise idk if this is alot of work to be put into but can possibly ensure this would help advance tiefix aswell.

EDIT: [A second list of bugs are here](https://pastebin.com/raw/d28Y40hW) as additional bugs were found directly from blanket + thorium thanks to @Julienraptor01.

**Comment by j-tai** [comment]
Thanks! I will see if I can add these. Some of them are already in the mod.

Copying the list here:

* [ ] MC-4490
* [ ] MC-46776
* [ ] MC-53312
* [ ] MC-79545
* [ ] MC-80859
* [ ] MC-93384
* [ ] MC-108948
* [ ] MC-111516
* [ ] MC-116379
* [ ] MC-121772
* [ ] MC-122627
* [ ] MC-123739
* [x] MC-122477
* [x] MC-127970
* [x] MC-140646
* [ ] MC-145748
* [x] MC-145929
* [ ] MC-147605
* [ ] MC-148149
* [x] MC-151412
* [ ] MC-159163
* [ ] MC-162253
* [ ] MC-165381
* [ ] MC-165595
* [ ] MC-176559
* [ ] MC-183776
* [ ] MC-197260
* [ ] MC-215531
* [ ] MC-217716
* [ ] MC-227169
* [ ] MC-231097
* [x] MC-233042
* [ ] MC-234898
* [ ] MC-235035
* [ ] MC-249021
* [ ] MC-249059

**Comment by Kichura** [comment]
Updated the main comment to include a secondary list.

**Comment by isXander** [comment]
bruh what
I removed telemetry because it was bad idea.
> using checks for bug fixes which i was dissatisified about
tf u mean

**Comment by isXander** [comment]
In that case, time to port over the whole of tiefix into Debugify because they decided to do the same.

**Comment by DragonEggBedrockBreaking** [comment]
> bruh what I removed telemetry because it was bad idea.

Your mod does not remove telemetry. This mod does. What’s your point?

**Comment by isXander** [comment]
> > bruh what I removed telemetry because it was bad idea.
> 
> Your mod does not remove telemetry. This mod does. What’s your point?

I believe Kichura is refering to something else, if not, ok.

**Comment by Kichura** [comment]
> > > bruh what I removed telemetry because it was bad idea.
> > 
> > 
> > Your mod does not remove telemetry. This mod does. What’s your point?
> 
> I believe Kichura is refering to something else, if not, ok.

I thought you stated earlier you will not disable it as it was intentional?, If not; then i think we had a miscommunication there or something, but i won't blame you for it.

**Comment by isXander** [comment]
Thought you were talking about when debugify had its own metrics lol.

As I've clearly seen that it's wanted from everyone. I have decided to add it. The reason why I originally didn't add it is because I would want it to be toggleable (which all bug fixes now are)

**Comment by Kichura** [comment]
> Thought you were talking about when debugify had its own metrics lol.
> 
> As I've clearly seen that it's wanted from everyone. I have decided to add it. The reason why I originally didn't add it is because I would want it to be toggleable (which all bug fixes now are)

In the telemetry context; i never really bothered any of it since i thought i could just overlay tiefix on top of it and be done with that,

as for the metrics part; i did kinda admit to it although this was because ztereo posted a image in a private convo of a dude who stated that your mod had something sus in it which kinda made me regret the usage of it. (before hand; i never knew any of this)

**Comment by Wyvest** [comment]
> > Thought you were talking about when debugify had its own metrics lol.
> > As I've clearly seen that it's wanted from everyone. I have decided to add it. The reason why I originally didn't add it is because I would want it to be toggleable (which all bug fixes now are)
> 
> In the telemetry context; i never really bothered any of it since i thought i could just overlay tiefix on top of it and be done with that,
> 
> as for the metrics part; i did kinda admit to it although this was because ztereo posted a image in a private convo of a dude who stated that your mod had something sus in it which kinda made me regret the usage of it. (before hand; i never knew any of this), but since it has matured a bit; i'm thinking of giving it another try although have to yet to decide upon but rn, i'm gonna stick with tiefix since i recognized it better.

If I may ask - what was so “sus” about Debugify? Debugify is fully open source,” and does (almost) nothing except fix bugs.

If I’m being completely honest, this seems very scummy, as this is literally intending to and just stealing Debugify.

**Comment by DragonEggBedrockBreaking** [comment]
> Debugify is fully open source

That statement is completely meaningless here. Open source projects can still have issues. What would have meaning is to say “I read through all of the source code, and decompiled all of the binaries, and I can find no issues”. If nobody checks the source code fully, open source projects can be as sus as proprietary proj3cts.

**Comment by DragonEggBedrockBreaking** [comment]
> If I’m being completely honest, this seems very scummy, as this is literally intending to and just stealing Debugify.

Well debugify has implemented almost all of tiefix, and continues to add more of its features. It did that way before this bug report was made. So I don’t understand the issue? Many of debugify’s features are from other mods.

**Comment by j-tai** [comment]
@isXander I’m sorry about that. If you want, I can stop using this list.

**Comment by Kichura** [comment]
Closing this due to tons of backlash caused by competitors.

**Comment by Kichura** [comment]
re-opening this as some people like altrisi weren't pleased with debugify.
